# Generated by Django 5.1.7 on 2025-08-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
