POST http://localhost:8000/api/token/ HTTP/1.1
content-type: application/json

{
    "username": "qe",
    "password": "123456"
}
###
POST http://localhost:8000/api/token/ HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "test"
}
###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
content-type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NjExNDM4NCwiaWF0IjoxNzU2MDI3OTg0LCJqdGkiOiJlNmIyMTAzYzQ2ODE0YzZkODBiYTk1ZjczYjJlMjk1NSIsInVzZXJfaWQiOiIyIn0.C1PcvKacSxoD9-Yn3bFHm5IFyoe2AqIYvBAzTRpiz6I"

}

###
POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NDkwNTcyLCJpYXQiOjE3NTU0OTAyNzIsImp0aSI6IjIxODU5MDllNDhjYzQzY2Q5OWE5NzQwZmJiMWJjYmNjIiwidXNlcl9pZCI6IjEifQ.G9Rem838jsmhuHLn5tH_o-n6LZZO8eTznN0C0PCo4pQ

{
    "name": "New Product",
    "price": 19.99,
    "stock": 100
}
###
GET http://localhost:8000/products/1/ HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/products/1/ HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "name": "A Scanner Darklly",
  "price": "12.99",
  "stock": 4
}

###
DELETE http://localhost:8000/products/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NTk4MzgwLCJpYXQiOjE3NTU1OTgwODAsImp0aSI6IjBlZWQ4NmY1N2E4YjQwNDNiYTdlYzE2MTcyZDc5ODY0IiwidXNlcl9pZCI6IjEifQ.NQf5H9syFf_OMzXPab-9QEypAB3xVmNyxB9fr_w47Ig
###
GET http://localhost:8000/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2NDgzNTQ2LCJpYXQiOjE3NTY0Nzk5NDYsImp0aSI6IjE0ZWU3MWJjODYzMDQ5MDdiZDg5NDA1NjY2OWU4MjM5IiwidXNlcl9pZCI6IjEifQ.dyRf_rN_Oj_qFS0M1lihFQKjloKBYo6lik5dW834jnA
Content-Type: Application/json

###
POST http://localhost:8000/orders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MDUyODgxLCJpYXQiOjE3NTYwNDkyODEsImp0aSI6Ijc2MWE4ZjUwZDVjODQ0YmU4ZDRlZDM2ODNjMTNiOGQ3IiwidXNlcl9pZCI6IjIifQ.Ap0ql1o52jX7HKlOpUuUrsN0beAgeB95gnhpm6N4zOo
Content-Type: application/json

{
  "status": "Pending",
  "items": [
    {
      "product": 4,
      "quantity": 4
    },
    {
      "product": 3,
      "quantity": 2
    }
  ]

}
###
PUT http://localhost:8000/orders/c6633334-5b3c-4da9-a378-ffd283bf485e/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MDUyODgxLCJpYXQiOjE3NTYwNDkyODEsImp0aSI6Ijc2MWE4ZjUwZDVjODQ0YmU4ZDRlZDM2ODNjMTNiOGQ3IiwidXNlcl9pZCI6IjIifQ.Ap0ql1o52jX7HKlOpUuUrsN0beAgeB95gnhpm6N4zOo
Content-Type: application/json

{
  "status": "Pending",
  "items": [
    {
      "product": 4,
      "quantity": 4
    },
    {
      "product": 3,
      "quantity": 2
    }
  ]

}